name: Java Build with Coverage

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Add necessary permissions for commenting on PRs
permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: Java 11 Build with Coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better code coverage accuracy
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven and Generate Coverage
      run: |
        mvn -B clean test org.jacoco:jacoco-maven-plugin:0.8.7:prepare-agent org.jacoco:jacoco-maven-plugin:0.8.7:report
      
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports
        
    # Upload coverage reports to Codecov.io for detailed analytics and historical tracking
    - name: Upload Coverage Reports (Codecov)
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Optional but recommended for better security and identification
        fail_ci_if_error: false
        flags: unittests
        name: codecov-umbrella
        verbose: true
        
    # Save coverage reports as GitHub artifacts
    - name: Upload Coverage Reports (GitHub)
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: '**/target/site/jacoco/index.html'
        
    # Post coverage reports directly as comments on the PR
    - name: Post Coverage Report to PR
      uses: madrapps/jacoco-report@v1.6.1
      with:
        paths: ${{ github.workspace }}/**/target/site/jacoco/jacoco.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 40
        min-coverage-changed-files: 60
        title: 'Code Coverage Report'
        update-comment: true 