name: MulticloudJ Build and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17, 21]
      fail-fast: false

    name: Java ${{ matrix.java }} Build

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    
    - name: Build and verify with Maven
      run: mvn -B -T 1 verify
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports-java-${{ matrix.java }}
        path: '**/target/surefire-reports/*.xml' 